# Define other files to be imported into WordPress
# 2 alternative formats:
# - /path/to/plugin/source
# - path: /path/to/plugin/source

plugins:
  - path: ./plugins/wp-session-manager
    # glob for files to watch
    watch: "**/*.{php,png,jpg}"
    # glob for files to copy
    include: "**"
    # glob for files to ignore
    exclude: "**/.git*"
